/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author espar
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Alta_Usuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_Registrar_evento = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Alta_Usuario.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Alta_Usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Alta_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Alta_Usuario.setText("Alta de usuario");
        jButton_Alta_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Alta_UsuarioMouseClicked(evt);
            }
        });
        jButton_Alta_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Alta_UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Alta_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 72, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona la opcion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 16, -1, -1));

        jButton_Registrar_evento.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Registrar_evento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Registrar_evento.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Registrar_evento.setText("Registrar evento");
        jButton_Registrar_evento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Registrar_eventoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Registrar_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 147, -1, -1));

        jButton_Salir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Salir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerebro-big-data.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton volver
    private void jButton_Alta_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Alta_UsuarioMouseClicked
        // TODO add your handling code here:
        //Interfaz_usuario..setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_jButton_Alta_UsuarioMouseClicked

    private void jButton_Registrar_eventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Registrar_eventoActionPerformed
       Tabla_registro ventana = new Tabla_registro();
       ventana.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton_Registrar_eventoActionPerformed

    private void jButton_Alta_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Alta_UsuarioActionPerformed
        // TODO add your handling code here:
        Alta_Usuario ventana = new Alta_Usuario ();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Alta_UsuarioActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Alta_Usuario;
    private javax.swing.JButton jButton_Registrar_evento;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
